<b> Curso Python para Machine Leaning - Didática Tech - <br> Vídeo: "Aprenda como usar o Numpy <br> (Python para machine learning - Aula 10)"</b><br>https://www.youtube.com/watch?v=CC4aco6zWic&list=PLyqOvdQmGdTR46HUxDA6Ymv4DGsIjvTQ-&index=10

## <b>Arrays - NumPy</b>

### Dimensões:

Cada par de chave, que determina uma lista, corresponde a uma dimensão;<br>
e a chave maior, que engloba todas as outras, corresponde ao parâmetro.

In [2]:
import numpy as np

In [34]:
primeiro = np.array([1, 2, 3]) # array de 1 unidimensional.
print(primeiro)

[1 2 3]


In [35]:
segundo = np.array([[1, 2, 3], [4, 5, 6]]) # array multidimensional.
print(segundo)

[[1 2 3]
 [4 5 6]]


In [4]:
terceiro = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # array multidimensional. 
print(terceiro)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
quarto = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) # array tridimensional - 3D.
print(quarto)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


<b>Mais infos sobre array, diretamente da documentação</b><br>https://numpy.org/doc/stable/user/absolute_beginners.html

<img src="imagens/array.png" width="600">

### Acessando elementos do array através dos índices:

In [9]:
quarto[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
quarto[1]

array([[ 7,  8,  9],
       [10, 11, 12]])