<b> Curso Python para Machine Leaning - Didática Tech - <br> Vídeo: "Aprenda como usar o Numpy <br> (Python para machine learning - Aula 10)"</b><br>https://www.youtube.com/watch?v=CC4aco6zWic&list=PLyqOvdQmGdTR46HUxDA6Ymv4DGsIjvTQ-&index=10

### <b>Arrays - NumPy</b>

Cada par de chave, que determina uma lista, corresponde a uma dimensão;<br>
e a chave maior, que engloba todas as outras, corresponde ao parâmetro.

In [33]:
import numpy as np

In [34]:
primeiro = np.array([1, 2, 3]) # array de 1 unidimensional.
print(primeiro)

[1 2 3]


In [35]:
segundo = np.array([[1, 2, 3], [4, 5, 6]]) # array multidimensional.
print(segundo)

[[1 2 3]
 [4 5 6]]


In [36]:
terceiro = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # array multidimensional. 
print(terceiro)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
quarto = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) # array tridimensional - 3D.
print(quarto)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
